# Generated by Django 5.1.3 on 2025-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
